"""Initial Schema

Revision ID: 2a3f0879b980
Revises: 
Create Date: 2026-07-26 19:43:00.253186+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3f0879b980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False, comment="BCP 47 language tag, e.g. 'en', 'tw', 'ha'."),
    sa.Column('name_en', sa.String(length=60), nullable=False, comment="Language name in English, e.g. 'English', 'Twi'."),
    sa.Column('name_native', sa.String(length=60), nullable=False, comment="Language name in the native script, e.g. 'Twi', 'English'."),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='Whether this language is currently enabled in the UI.'),
    sa.Column('supports_voice', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Whether voice input / TTS is supported for this language.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_languages_code'),
    comment='Supported application languages. Extended via migration, never via seed.'
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=False)
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('rule_trees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tree_structure', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_trees_version'), 'rule_trees', ['version'], unique=True)
    op.create_table('severity_levels',
    sa.Column('code', sa.Enum('RED', 'ORANGE', 'YELLOW', 'GREEN', name='urgency_code_enum'), nullable=False, comment='Canonical urgency code (RED/ORANGE/YELLOW/GREEN).'),
    sa.Column('label_en', sa.String(length=60), nullable=False, comment="Display label in English, e.g. 'Emergency', 'Very Urgent'."),
    sa.Column('label_tw', sa.String(length=60), nullable=True, comment='Display label in Twi.'),
    sa.Column('description_en', sa.String(length=500), nullable=True, comment='Clinical description shown in triage result card.'),
    sa.Column('badge_color_hex', sa.String(length=9), nullable=False, comment="CSS hex color for UI urgency badge, e.g. '#DC2626'."),
    sa.Column('timeframe_minutes', sa.Integer(), nullable=False, comment='Maximum recommended care timeframe in minutes (0 = immediate).'),
    sa.Column('requires_emergency_dispatch', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True only for RED — triggers GPS, SMS, and Emergency Centre.'),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='Sort order for admin dashboard severity filter display.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_severity_levels_code'),
    comment='Configuration table for the four MTS urgency levels. Exactly four rows — one per UrgencyCode enum value.'
    )
    op.create_index(op.f('ix_severity_levels_code'), 'severity_levels', ['code'], unique=True)
    op.create_index(op.f('ix_severity_levels_id'), 'severity_levels', ['id'], unique=False)
    op.create_table('symptom_categories',
    sa.Column('name_en', sa.String(length=100), nullable=False, comment='Category display name in English.'),
    sa.Column('name_tw', sa.String(length=100), nullable=True, comment='Category display name in Twi.'),
    sa.Column('slug', sa.String(length=80), nullable=False, comment="URL-safe kebab-case identifier, e.g. 'chest-pain'."),
    sa.Column('body_system', sa.Enum('CARDIOVASCULAR', 'RESPIRATORY', 'NEUROLOGICAL', 'GASTROINTESTINAL', 'MUSCULOSKELETAL', 'DERMATOLOGICAL', 'ENDOCRINE', 'REPRODUCTIVE', 'UROLOGICAL', 'MENTAL_HEALTH', 'OPHTHALMOLOGICAL', 'ENT', 'HAEMATOLOGICAL', 'INFECTIOUS', 'OTHER', name='body_system_enum'), nullable=False, comment='Clinical body system this category belongs to.'),
    sa.Column('icon_name', sa.String(length=60), nullable=True, comment='Material / Lucide icon name for UI rendering.'),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='Sort order for symptom picker display.'),
    sa.Column('is_emergency_fast_track', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='If True, this category bypasses standard flow and opens Emergency Centre immediately.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_symptom_categories_slug'),
    comment='Clinical category groupings for symptom picker UI and decision tree routing.'
    )
    op.create_index(op.f('ix_symptom_categories_body_system'), 'symptom_categories', ['body_system'], unique=False)
    op.create_index(op.f('ix_symptom_categories_id'), 'symptom_categories', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_categories_is_deleted'), 'symptom_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_symptom_categories_slug'), 'symptom_categories', ['slug'], unique=True)
    op.create_table('health_concerns',
    sa.Column('severity_level_id', sa.String(length=36), nullable=False, comment='Default severity level assigned when this concern is identified.'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe identifier, e.g. 'possible-cardiac-event'."),
    sa.Column('name_en', sa.String(length=200), nullable=False, comment="Concern name in English, e.g. 'Possible Cardiac Event'."),
    sa.Column('name_tw', sa.String(length=200), nullable=True, comment='Concern name in Twi.'),
    sa.Column('description_en', sa.String(length=1000), nullable=True, comment='Clinical description used in AI explanation context.'),
    sa.Column('requires_emergency_dispatch', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='If True, immediately opens Emergency Centre on identification.'),
    sa.Column('icd10_code', sa.String(length=10), nullable=True, comment='ICD-10 code for clinical interoperability.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.id'], name='fk_health_concerns_severity_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_health_concerns_slug'),
    comment='Named clinical health concerns produced by rule engine evaluation. Each concern is linked to a severity level and recommendation set.'
    )
    op.create_index(op.f('ix_health_concerns_icd10_code'), 'health_concerns', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_health_concerns_id'), 'health_concerns', ['id'], unique=False)
    op.create_index(op.f('ix_health_concerns_is_deleted'), 'health_concerns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_health_concerns_severity_level_id'), 'health_concerns', ['severity_level_id'], unique=False)
    op.create_index(op.f('ix_health_concerns_slug'), 'health_concerns', ['slug'], unique=True)
    op.create_table('symptoms',
    sa.Column('category_id', sa.String(length=36), nullable=False, comment='Owning symptom category UUID.'),
    sa.Column('slug', sa.String(length=80), nullable=False, comment="URL-safe identifier, e.g. 'chest-pain', 'severe-bleeding'."),
    sa.Column('name_en', sa.String(length=150), nullable=False, comment='Symptom display name in English (canonical).'),
    sa.Column('description_en', sa.String(length=500), nullable=True, comment='Brief clinical description in English.'),
    sa.Column('severity_hint', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='symptom_severity_hint_enum'), server_default='MODERATE', nullable=False, comment='Pre-evaluation severity hint for UI badge coloring.'),
    sa.Column('is_red_flag', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='If True, selecting this symptom immediately triggers Emergency Centre.'),
    sa.Column('icd10_code', sa.String(length=10), nullable=True, comment="ICD-10 code for clinical interoperability, e.g. 'R07.4'."),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False, comment='Sort order within the parent category.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='Inactive symptoms are hidden from the UI picker.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['category_id'], ['symptom_categories.id'], name='fk_symptoms_category_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_symptoms_slug'),
    comment='Clinical symptoms that trigger triage decision tree evaluations.'
    )
    op.create_index(op.f('ix_symptoms_category_id'), 'symptoms', ['category_id'], unique=False)
    op.create_index(op.f('ix_symptoms_icd10_code'), 'symptoms', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_symptoms_id'), 'symptoms', ['id'], unique=False)
    op.create_index(op.f('ix_symptoms_is_deleted'), 'symptoms', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_symptoms_is_red_flag'), 'symptoms', ['is_red_flag'], unique=False)
    op.create_index(op.f('ix_symptoms_slug'), 'symptoms', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='E.164 format phone number used as login identifier.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Argon2id password hash. Never store plaintext.'),
    sa.Column('role', sa.Enum('PATIENT', 'HEALTH_WORKER', 'ADMIN', name='user_role_enum'), server_default='PATIENT', nullable=False, comment='Access control role for the user.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='False if account is suspended or pending verification.'),
    sa.Column('full_name', sa.String(length=120), nullable=True, comment='Display name. Optional — not required for anonymous triage.'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Age in years. Used for paediatric and geriatric rule weighting.'),
    sa.Column('biological_sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='biological_sex_enum'), nullable=True, comment='Biological sex for sex-linked clinical rule evaluation.'),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='blood_group_enum'), nullable=True, comment='ABO + Rh blood group. Optional clinical context.'),
    sa.Column('preferred_language_code', sa.String(length=10), server_default='en', nullable=False, comment="BCP 47 code of the user's preferred UI language."),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['preferred_language_code'], ['languages.code'], onupdate='CASCADE', ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_users_phone_number'),
    comment='Authenticated user accounts. PII is split into health_profiles.'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Authenticated user UUID. NULL for anonymous triage sessions.'),
    sa.Column('symptom_id', sa.String(length=36), nullable=True, comment='Primary symptom selected as the decision tree entry point.'),
    sa.Column('identified_concern_id', sa.String(length=36), nullable=True, comment='HealthConcern identified by the rule engine. NULL if evaluation incomplete.'),
    sa.Column('severity_level_id', sa.String(length=36), nullable=True, comment='Final severity level assigned to this session.'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'SYNCED', name='session_status_enum'), server_default='IN_PROGRESS', nullable=False, comment='Lifecycle status of this assessment session.'),
    sa.Column('consultation_mode', sa.Enum('TEXT', 'VOICE', 'HYBRID', name='consultation_mode_enum'), server_default='TEXT', nullable=False, comment='Interaction mode used during this session.'),
    sa.Column('language_code', sa.String(length=10), server_default='en', nullable=False, comment='BCP 47 language code active during this session.'),
    sa.Column('created_offline', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True if this session was created while the client was offline.'),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the session was actually conducted (may predate sync).'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this offline session was synced to the server.'),
    sa.Column('client_session_id', sa.String(length=36), nullable=True, comment='Client-side UUID for idempotent offline outbox sync.'),
    sa.Column('ai_explanation', sa.Text(), nullable=True, comment='Gemini AI generated contextual explanation (Phase 2).'),
    sa.Column('raw_answers_snapshot', sa.JSON(), nullable=True, comment='Complete node_id→answer_value snapshot for rule engine audit trail.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['identified_concern_id'], ['health_concerns.id'], name='fk_assessment_sessions_concern_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.id'], name='fk_assessment_sessions_severity_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_assessment_sessions_symptom_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_assessment_sessions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Canonical triage assessment session records. Supports offline-first creation with deferred sync.'
    )
    op.create_index(op.f('ix_assessment_sessions_client_session_id'), 'assessment_sessions', ['client_session_id'], unique=True)
    op.create_index(op.f('ix_assessment_sessions_created_offline'), 'assessment_sessions', ['created_offline'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_id'), 'assessment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_identified_concern_id'), 'assessment_sessions', ['identified_concern_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_is_deleted'), 'assessment_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_severity_level_id'), 'assessment_sessions', ['severity_level_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_status'), 'assessment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_symptom_id'), 'assessment_sessions', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_user_id'), 'assessment_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Actor user UUID. NULL for anonymous or system-generated events.'),
    sa.Column('action', sa.Enum('USER_REGISTERED', 'USER_LOGIN_SUCCESS', 'USER_LOGIN_FAILURE', 'USER_LOGOUT', 'PASSWORD_CHANGED', 'PROFILE_CREATED', 'PROFILE_UPDATED', 'EMERGENCY_CONTACT_ADDED', 'EMERGENCY_CONTACT_REMOVED', 'ASSESSMENT_STARTED', 'ASSESSMENT_COMPLETED', 'EMERGENCY_DISPATCHED', 'USER_DEACTIVATED', 'USER_ROLE_CHANGED', 'USER_DATA_DELETED', 'OFFLINE_SYNC_COMPLETED', name='audit_action_enum'), nullable=False, comment='Classified audit event type.'),
    sa.Column('resource_type', sa.String(length=60), nullable=True, comment="Resource type affected, e.g. 'User', 'AssessmentSession'."),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='UUID of the specific resource instance affected.'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this event occurred.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Requester IPv4/IPv6 address (max 45 chars covers IPv6).'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='HTTP User-Agent header of the client that triggered the event.'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Arbitrary event context payload (e.g. changed field names, new values).'),
    sa.Column('outcome', sa.String(length=20), nullable=True, comment="Event outcome: 'SUCCESS', 'FAILURE', 'PARTIAL'."),
    sa.Column('notes', sa.Text(), nullable=True, comment='Human-readable summary of the event for admin review.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable audit trail. INSERT ONLY — no updates or deletes permitted. Required for GDPR Article 30 (Records of processing activities).'
    )
    op.create_index('idx_audit_logs_occurred_at', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('idx_audit_logs_user_id_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Owning user UUID.'),
    sa.Column('contact_name', sa.String(length=100), nullable=False, comment='Full name of the emergency contact person.'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='E.164 phone number for SMS dispatch.'),
    sa.Column('relationship_type', sa.Enum('SPOUSE', 'PARENT', 'CHILD', 'SIBLING', 'FRIEND', 'COLLEAGUE', 'HEALTHCARE_PROVIDER', 'OTHER', name='relationship_type_enum'), server_default='OTHER', nullable=False, comment='Relationship of this contact to the patient.'),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True for the single primary contact who receives first-priority SMS.'),
    sa.Column('notes', sa.String(length=255), nullable=True, comment="Optional free-text notes about this contact (e.g. 'Speaks Twi only')."),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_emergency_contacts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Emergency contacts registered by users. Max 5 per user enforced at service layer. Primary contact receives the first SMS dispatch on RED urgency.'
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_is_primary'), 'emergency_contacts', ['is_primary'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('biological_sex', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('known_allergies', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('symptom_id', sa.String(length=36), nullable=False, comment='Symptom decision tree this question belongs to.'),
    sa.Column('node_id', sa.String(length=100), nullable=False, comment="Stable node ID matching the JSON rule tree structure, e.g. 'node_chest_pain_qualifier'."),
    sa.Column('question_text_en', sa.Text(), nullable=False, comment='Question text in English (canonical).'),
    sa.Column('question_text_tw', sa.Text(), nullable=True, comment='Question text in Twi.'),
    sa.Column('voice_prompt_en', sa.Text(), nullable=True, comment='TTS-optimized English question for voice mode.'),
    sa.Column('voice_prompt_tw', sa.Text(), nullable=True, comment='TTS-optimized Twi question for voice mode.'),
    sa.Column('question_type', sa.Enum('SINGLE_SELECT', 'MULTI_SELECT', 'BOOLEAN', 'NUMERIC', 'TEXT', name='question_type_enum'), server_default='SINGLE_SELECT', nullable=False, comment='UI control type for rendering the answer widget.'),
    sa.Column('is_red_flag_trigger', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='If True, certain answers to this question trigger immediate RED urgency.'),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='If True, patient must answer before proceeding.'),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False, comment="Display order within this symptom's decision tree."),
    sa.Column('help_text_en', sa.String(length=500), nullable=True, comment='Optional clinical help text shown below the question.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_questions_symptom_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Decision tree node questions for symptom evaluation flows. Ordered by order_index within each symptom tree.'
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_is_deleted'), 'questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_questions_node_id'), 'questions', ['node_id'], unique=False)
    op.create_index(op.f('ix_questions_order_index'), 'questions', ['order_index'], unique=False)
    op.create_index(op.f('ix_questions_symptom_id'), 'questions', ['symptom_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('health_concern_id', sa.String(length=36), nullable=False, comment='Parent health concern UUID.'),
    sa.Column('recommendation_type', sa.Enum('PRIMARY_ACTION', 'FIRST_AID_STEP', 'SELF_CARE', 'MONITORING', 'REFERRAL', 'DO_NOT', name='recommendation_type_enum'), nullable=False, comment='Classifies the recommendation for rendering in the correct UI section.'),
    sa.Column('content_en', sa.Text(), nullable=False, comment='Recommendation text in English (canonical).'),
    sa.Column('step_order', sa.Integer(), server_default='0', nullable=False, comment='Display order for FIRST_AID_STEP type recommendations.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='Inactive recommendations are excluded from result cards.'),
    sa.Column('source_reference', sa.String(length=255), nullable=True, comment="Clinical evidence source (e.g. 'WHO First Aid Guidelines 2021, p.42')."),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['health_concern_id'], ['health_concerns.id'], name='fk_recommendations_concern_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Clinical recommendations displayed on triage result cards. Multiple recommendation types per health concern are supported.'
    )
    op.create_index(op.f('ix_recommendations_health_concern_id'), 'recommendations', ['health_concern_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_is_deleted'), 'recommendations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_table('symptom_concerns',
    sa.Column('symptom_id', sa.String(length=36), nullable=False, comment='Symptom UUID.'),
    sa.Column('health_concern_id', sa.String(length=36), nullable=False, comment='HealthConcern UUID.'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Diagnostic association weight (0.0 = weak, 1.0 = definitive).'),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False, comment='Evaluation priority order for this symptom within the concern.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['health_concern_id'], ['health_concerns.id'], name='fk_symptom_concerns_concern_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_symptom_concerns_symptom_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_id', 'health_concern_id', name='uq_symptom_concerns_pair'),
    comment='Association table mapping symptoms to health concerns. Weight (0.0–1.0) represents diagnostic association strength.'
    )
    op.create_index(op.f('ix_symptom_concerns_health_concern_id'), 'symptom_concerns', ['health_concern_id'], unique=False)
    op.create_index(op.f('ix_symptom_concerns_id'), 'symptom_concerns', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_concerns_symptom_id'), 'symptom_concerns', ['symptom_id'], unique=False)
    op.create_table('symptom_translations',
    sa.Column('symptom_id', sa.String(length=36), nullable=False, comment='Symptom this translation belongs to.'),
    sa.Column('language_code', sa.String(length=10), nullable=False, comment='BCP 47 language code for this translation.'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Localized symptom display name.'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Localized brief clinical description shown in the symptom picker.'),
    sa.Column('voice_prompt', sa.String(length=300), nullable=True, comment='TTS-optimized text for voice consultation mode in this language.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name='fk_symptom_translations_lang_code', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_symptom_translations_symptom_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_id', 'language_code', name='uq_symptom_translations_symptom_lang'),
    comment='One row per symptom-language pair. Provides translated name and description for symptom picker UI.'
    )
    op.create_index(op.f('ix_symptom_translations_id'), 'symptom_translations', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_translations_language_code'), 'symptom_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_symptom_translations_symptom_id'), 'symptom_translations', ['symptom_id'], unique=False)
    op.create_table('triage_rules',
    sa.Column('symptom_id', sa.String(length=36), nullable=False, comment='Primary symptom this rule applies to.'),
    sa.Column('severity_level_id', sa.String(length=36), nullable=False, comment='Severity level assigned when this rule matches.'),
    sa.Column('health_concern_id', sa.String(length=36), nullable=True, comment='Health concern identified when this rule matches (optional).'),
    sa.Column('rule_name', sa.String(length=200), nullable=False, comment="Human-readable rule name for admin UI, e.g. 'Chest Pain + Dyspnoea → RED'."),
    sa.Column('rule_conditions', sa.JSON(), nullable=False, comment='JSONB list of condition objects: [{node_id: str, answer_value: str, negated: bool}]. Empty list = match always (catch-all rule).'),
    sa.Column('logic_operator', sa.Enum('AND', 'OR', name='rule_logic_operator_enum'), server_default='AND', nullable=False, comment='AND = all conditions must match; OR = any condition must match.'),
    sa.Column('priority_order', sa.Integer(), server_default='100', nullable=False, comment='Evaluation priority — lower values are checked first.'),
    sa.Column('is_red_flag_override', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='If True, this rule short-circuits all other rules and returns RED immediately.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False, comment='Inactive rules are excluded from evaluation.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Clinical rationale or source reference for this rule.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['health_concern_id'], ['health_concerns.id'], name='fk_triage_rules_concern_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.id'], name='fk_triage_rules_severity_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_triage_rules_symptom_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Clinical decision rules evaluated by the rule engine. Lower priority_order values are evaluated first.'
    )
    op.create_index(op.f('ix_triage_rules_health_concern_id'), 'triage_rules', ['health_concern_id'], unique=False)
    op.create_index(op.f('ix_triage_rules_id'), 'triage_rules', ['id'], unique=False)
    op.create_index(op.f('ix_triage_rules_is_active'), 'triage_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_triage_rules_is_deleted'), 'triage_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_triage_rules_priority_order'), 'triage_rules', ['priority_order'], unique=False)
    op.create_index(op.f('ix_triage_rules_severity_level_id'), 'triage_rules', ['severity_level_id'], unique=False)
    op.create_index(op.f('ix_triage_rules_symptom_id'), 'triage_rules', ['symptom_id'], unique=False)
    op.create_table('triage_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('rule_tree_id', sa.String(length=36), nullable=True),
    sa.Column('urgency_level', sa.String(length=10), nullable=False),
    sa.Column('primary_symptom', sa.String(length=100), nullable=False),
    sa.Column('symptom_details', sa.JSON(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('created_offline', sa.Boolean(), nullable=False),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_tree_id'], ['rule_trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_sessions_urgency_level'), 'triage_sessions', ['urgency_level'], unique=False)
    op.create_index(op.f('ix_triage_sessions_user_id'), 'triage_sessions', ['user_id'], unique=False)
    op.create_table('emergency_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('triage_session_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['triage_session_id'], ['triage_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('triage_session_id')
    )
    op.create_table('question_options',
    sa.Column('question_id', sa.String(length=36), nullable=False, comment='Parent question UUID.'),
    sa.Column('terminal_severity_level_id', sa.String(length=36), nullable=True, comment='Severity level produced if this is a terminal option. NULL if non-terminal.'),
    sa.Column('option_value', sa.String(length=100), nullable=False, comment='Machine-readable answer value stored in AssessmentResponse.'),
    sa.Column('label_en', sa.String(length=200), nullable=False, comment='Option display label in English.'),
    sa.Column('label_tw', sa.String(length=200), nullable=True, comment='Option display label in Twi.'),
    sa.Column('next_node_id', sa.String(length=100), nullable=True, comment='Node ID of the next question if this option is selected. NULL if terminal.'),
    sa.Column('is_terminal', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True if selecting this option ends the decision tree evaluation.'),
    sa.Column('is_red_flag', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True if selecting this option immediately triggers RED urgency override.'),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False, comment='Display order of this option within its parent question.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_question_options_question_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_severity_level_id'], ['severity_levels.id'], name='fk_question_options_severity_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Answer options for clinical decision tree questions. Option may route to next question, terminate, or trigger emergency.'
    )
    op.create_index(op.f('ix_question_options_id'), 'question_options', ['id'], unique=False)
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_options_terminal_severity_level_id'), 'question_options', ['terminal_severity_level_id'], unique=False)
    op.create_table('recommendation_translations',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False, comment='Parent recommendation UUID.'),
    sa.Column('language_code', sa.String(length=10), nullable=False, comment='BCP 47 language code.'),
    sa.Column('content', sa.Text(), nullable=False, comment='Localized recommendation text.'),
    sa.Column('voice_content', sa.Text(), nullable=True, comment='TTS-optimized version for voice consultation mode.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name='fk_rec_translations_lang_code', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name='fk_rec_translations_recommendation_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'language_code', name='uq_rec_translations_rec_lang'),
    comment='Localized recommendation text per language. One row per recommendation-language pair.'
    )
    op.create_index(op.f('ix_recommendation_translations_id'), 'recommendation_translations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_translations_language_code'), 'recommendation_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_recommendation_translations_recommendation_id'), 'recommendation_translations', ['recommendation_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Parent assessment session UUID.'),
    sa.Column('question_id', sa.String(length=36), nullable=True, comment='Question that was answered. NULL if question was deleted after session.'),
    sa.Column('selected_option_id', sa.String(length=36), nullable=True, comment='QuestionOption selected. NULL for free-text or numeric responses.'),
    sa.Column('node_id', sa.String(length=100), nullable=False, comment='Node ID from the decision tree (matches question.node_id).'),
    sa.Column('answer_value', sa.String(length=500), nullable=False, comment='Selected answer value (option_value, free-text, or numeric string).'),
    sa.Column('answer_raw_text', sa.Text(), nullable=True, comment='Voice transcription raw text for VOICE mode responses.'),
    sa.Column('triggered_red_flag', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='True if this answer triggered a red-flag override.'),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this answer was recorded.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_assessment_responses_question_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], name='fk_assessment_responses_option_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], name='fk_assessment_responses_session_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='One row per question answered during a triage session. Provides full audit trail for rule engine evaluation and AI explanation.'
    )
    op.create_index(op.f('ix_assessment_responses_id'), 'assessment_responses', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_node_id'), 'assessment_responses', ['node_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_question_id'), 'assessment_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_selected_option_id'), 'assessment_responses', ['selected_option_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_session_id'), 'assessment_responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_responses_session_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_selected_option_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_question_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_node_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_recommendation_translations_recommendation_id'), table_name='recommendation_translations')
    op.drop_index(op.f('ix_recommendation_translations_language_code'), table_name='recommendation_translations')
    op.drop_index(op.f('ix_recommendation_translations_id'), table_name='recommendation_translations')
    op.drop_table('recommendation_translations')
    op.drop_index(op.f('ix_question_options_terminal_severity_level_id'), table_name='question_options')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_index(op.f('ix_question_options_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_table('emergency_logs')
    op.drop_index(op.f('ix_triage_sessions_user_id'), table_name='triage_sessions')
    op.drop_index(op.f('ix_triage_sessions_urgency_level'), table_name='triage_sessions')
    op.drop_table('triage_sessions')
    op.drop_index(op.f('ix_triage_rules_symptom_id'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_severity_level_id'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_priority_order'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_is_deleted'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_is_active'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_id'), table_name='triage_rules')
    op.drop_index(op.f('ix_triage_rules_health_concern_id'), table_name='triage_rules')
    op.drop_table('triage_rules')
    op.drop_index(op.f('ix_symptom_translations_symptom_id'), table_name='symptom_translations')
    op.drop_index(op.f('ix_symptom_translations_language_code'), table_name='symptom_translations')
    op.drop_index(op.f('ix_symptom_translations_id'), table_name='symptom_translations')
    op.drop_table('symptom_translations')
    op.drop_index(op.f('ix_symptom_concerns_symptom_id'), table_name='symptom_concerns')
    op.drop_index(op.f('ix_symptom_concerns_id'), table_name='symptom_concerns')
    op.drop_index(op.f('ix_symptom_concerns_health_concern_id'), table_name='symptom_concerns')
    op.drop_table('symptom_concerns')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_deleted'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_health_concern_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_questions_symptom_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_order_index'), table_name='questions')
    op.drop_index(op.f('ix_questions_node_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_deleted'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_is_primary'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_occurred_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessment_sessions_user_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_symptom_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_status'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_severity_level_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_is_deleted'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_identified_concern_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_created_offline'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_client_session_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptoms_slug'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_is_red_flag'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_is_deleted'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_id'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_icd10_code'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_category_id'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_health_concerns_slug'), table_name='health_concerns')
    op.drop_index(op.f('ix_health_concerns_severity_level_id'), table_name='health_concerns')
    op.drop_index(op.f('ix_health_concerns_is_deleted'), table_name='health_concerns')
    op.drop_index(op.f('ix_health_concerns_id'), table_name='health_concerns')
    op.drop_index(op.f('ix_health_concerns_icd10_code'), table_name='health_concerns')
    op.drop_table('health_concerns')
    op.drop_index(op.f('ix_symptom_categories_slug'), table_name='symptom_categories')
    op.drop_index(op.f('ix_symptom_categories_is_deleted'), table_name='symptom_categories')
    op.drop_index(op.f('ix_symptom_categories_id'), table_name='symptom_categories')
    op.drop_index(op.f('ix_symptom_categories_body_system'), table_name='symptom_categories')
    op.drop_table('symptom_categories')
    op.drop_index(op.f('ix_severity_levels_id'), table_name='severity_levels')
    op.drop_index(op.f('ix_severity_levels_code'), table_name='severity_levels')
    op.drop_table('severity_levels')
    op.drop_index(op.f('ix_rule_trees_version'), table_name='rule_trees')
    op.drop_table('rule_trees')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
