"""add auth fields

Revision ID: 3fc59d9f5a0a
Revises: 2a3f0879b980
Create Date: 2026-07-26 23:11:56.469685+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc59d9f5a0a'
down_revision: Union[str, None] = '2a3f0879b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True, comment='Optional email address for login/recovery.'))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when phone was verified (OTP).'))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when email was verified.'))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True if the user has completed their health profile.'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               comment='Display name. Required for registration.',
               existing_comment='Display name. Optional — not required for anonymous triage.')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               comment='Display name. Optional — not required for anonymous triage.',
               existing_comment='Display name. Required for registration.')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
