"""refactor assessment session to health conversation

Revision ID: fda41c51093d
Revises: e09ee8c91559
Create Date: 2026-07-29 13:58:36.945629+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fda41c51093d'
down_revision: Union[str, None] = 'e09ee8c91559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_conversations',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'ACTIVE', 'COMPLETED', 'ABANDONED', 'ARCHIVED', 'SYNCED', name='conversation_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('consultation_mode', sa.Enum('TEXT', 'VOICE', 'HYBRID', name='consultation_mode_enum'), server_default='TEXT', nullable=False),
    sa.Column('language_code', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('created_offline', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_session_id', sa.String(length=36), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('raw_answers_snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='Soft-delete flag. True means the record is logically deleted.'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when this record was soft-deleted. NULL if active.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_health_conversations_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_conversations_client_session_id'), 'health_conversations', ['client_session_id'], unique=True)
    op.create_index(op.f('ix_health_conversations_created_offline'), 'health_conversations', ['created_offline'], unique=False)
    op.create_index(op.f('ix_health_conversations_id'), 'health_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_health_conversations_is_deleted'), 'health_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_health_conversations_status'), 'health_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_health_conversations_user_id'), 'health_conversations', ['user_id'], unique=False)
    op.create_table('conversation_symptoms',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_id', sa.String(length=36), nullable=False),
    sa.Column('identified_concern_id', sa.String(length=36), nullable=True),
    sa.Column('severity_level_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key — UUID v4 string representation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the record was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update.'),
    sa.ForeignKeyConstraint(['conversation_id'], ['health_conversations.id'], name='fk_conv_symp_conversation_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identified_concern_id'], ['health_concerns.id'], name='fk_conv_symp_concern_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.id'], name='fk_conv_symp_severity_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name='fk_conv_symp_symptom_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_symptoms_conversation_id'), 'conversation_symptoms', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_symptoms_id'), 'conversation_symptoms', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_symptoms_symptom_id'), 'conversation_symptoms', ['symptom_id'], unique=False)
    op.drop_index(op.f('ix_assessment_sessions_client_session_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_created_offline'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_identified_concern_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_is_deleted'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_severity_level_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_status'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_symptom_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_user_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.add_column('assessment_responses', sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='Parent health conversation UUID.'))
    op.add_column('assessment_responses', sa.Column('symptom_id', sa.String(length=36), nullable=True, comment='Symptom this response pertains to.'))
    op.drop_index(op.f('ix_assessment_responses_session_id'), table_name='assessment_responses')
    op.create_index(op.f('ix_assessment_responses_conversation_id'), 'assessment_responses', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_symptom_id'), 'assessment_responses', ['symptom_id'], unique=False)
    op.drop_constraint(op.f('fk_assessment_responses_session_id'), 'assessment_responses', type_='foreignkey')
    op.create_foreign_key('fk_assessment_responses_symptom_id', 'assessment_responses', 'symptoms', ['symptom_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_assessment_responses_conversation_id', 'assessment_responses', 'health_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assessment_responses', 'session_id')
    # SQLite workaround: skip users alterations
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite workaround: skip users alterations
    op.add_column('assessment_responses', sa.Column('session_id', sa.VARCHAR(length=36), nullable=False))
    op.drop_constraint('fk_assessment_responses_conversation_id', 'assessment_responses', type_='foreignkey')
    op.drop_constraint('fk_assessment_responses_symptom_id', 'assessment_responses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_assessment_responses_session_id'), 'assessment_responses', 'assessment_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assessment_responses_symptom_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_conversation_id'), table_name='assessment_responses')
    op.create_index(op.f('ix_assessment_responses_session_id'), 'assessment_responses', ['session_id'], unique=False)
    op.drop_column('assessment_responses', 'symptom_id')
    op.drop_column('assessment_responses', 'conversation_id')
    op.create_table('assessment_sessions',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('symptom_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('identified_concern_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('severity_level_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), server_default=sa.text("'IN_PROGRESS'"), nullable=False),
    sa.Column('consultation_mode', sa.VARCHAR(length=6), server_default=sa.text("'TEXT'"), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_offline', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('conducted_at', sa.DATETIME(), nullable=False),
    sa.Column('synced_at', sa.DATETIME(), nullable=True),
    sa.Column('client_session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('ai_explanation', sa.TEXT(), nullable=True),
    sa.Column('raw_answers_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['identified_concern_id'], ['health_concerns.id'], name=op.f('fk_assessment_sessions_concern_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.id'], name=op.f('fk_assessment_sessions_severity_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('fk_assessment_sessions_symptom_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_user_id'), 'assessment_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_symptom_id'), 'assessment_sessions', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_status'), 'assessment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_severity_level_id'), 'assessment_sessions', ['severity_level_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_is_deleted'), 'assessment_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_identified_concern_id'), 'assessment_sessions', ['identified_concern_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_id'), 'assessment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_created_offline'), 'assessment_sessions', ['created_offline'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_client_session_id'), 'assessment_sessions', ['client_session_id'], unique=1)
    op.drop_index(op.f('ix_conversation_symptoms_symptom_id'), table_name='conversation_symptoms')
    op.drop_index(op.f('ix_conversation_symptoms_id'), table_name='conversation_symptoms')
    op.drop_index(op.f('ix_conversation_symptoms_conversation_id'), table_name='conversation_symptoms')
    op.drop_table('conversation_symptoms')
    op.drop_index(op.f('ix_health_conversations_user_id'), table_name='health_conversations')
    op.drop_index(op.f('ix_health_conversations_status'), table_name='health_conversations')
    op.drop_index(op.f('ix_health_conversations_is_deleted'), table_name='health_conversations')
    op.drop_index(op.f('ix_health_conversations_id'), table_name='health_conversations')
    op.drop_index(op.f('ix_health_conversations_created_offline'), table_name='health_conversations')
    op.drop_index(op.f('ix_health_conversations_client_session_id'), table_name='health_conversations')
    op.drop_table('health_conversations')
    # ### end Alembic commands ###
