/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

// Explicitly declare the self variable for the service worker context
declare const self: ServiceWorkerGlobalScope

clientsClaim()
self.skipWaiting()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// Fallback to index.html for navigation requests (SPA routing)
try {
  const handler = createHandlerBoundToURL('/index.html')
  const navigationRoute = new NavigationRoute(handler)
  registerRoute(navigationRoute)
} catch (e) {
  console.warn("Failed to register navigation route:", e)
}

