/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { registerRoute } from 'workbox-routing'
import { NetworkOnly } from 'workbox-strategies'

// Explicitly declare the self variable for the service worker context
declare const self: ServiceWorkerGlobalScope

clientsClaim()
self.skipWaiting()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// ── Background Sync for Triage Assessments ────────────────────────────────────

// Define a background sync queue for offline triage assessments
const triageBgSync = new BackgroundSyncPlugin('triage-outbox', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
})

// Intercept POST requests to the assessment endpoints and apply the background sync plugin
registerRoute(
  ({ request, url }) => url.pathname.includes('/api/v1/assessment') && request.method === 'POST',
  new NetworkOnly({
    plugins: [triageBgSync],
  })
)
