/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'


// Explicitly declare the self variable for the service worker context
declare const self: ServiceWorkerGlobalScope

clientsClaim()
self.skipWaiting()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

